ahoyapi: v1
version: 0.0.0
commands:
  hello:
    cmd: |
      docker exec -it $(docker-compose ps -q cli) bash -c "{{args}}"
    usage: Say hello.
  up:
    cmd: "docker-compose up -d"
    usage: Start the docker-compose containers.
  proxy-up:
    cmd: "docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy"
    usage: Run the nginx-proxy container
  stop:
    cmd: "docker-compose stop"
    usage: Stop the docker-compose containers (non-destructive).
  ps:
    cmd: "docker-compose ps"
    usage: List the running docker-compose containers.
  ip:
    cmd: "docker-machine ip default"
    usage: Show the ip address f the default docker machine VM
  reset:
    cmd: "docker-compose stop && docker-compose rm && ahoy up"
    usage: Start the docker compose-containers.
  drush:
    cmd: "docker-compose run cli drush --root=docroot {{args}}"
    usage: run drush commands in the cli service container.
  bash:
    cmd: "docker-compose run {{args}} bash "
    usage: run drush commands in the cli service container.
  mysql:
    cmd: "docker exec -it $(docker-compose ps -q cli) bash -c 'mysql -u$DB_ENV_MYSQL_USER -p$DB_ENV_MYSQL_PASSWORD -h$DB_PORT_3306_TCP_ADDR $DB_ENV_MYSQL_DATABASE'"
    usage: Connect to the default mysql database.
  mysql-import:
    cmd: "docker exec -i $(docker-compose ps -q cli) bash -c 'mysql -u$DB_ENV_MYSQL_USER -p$DB_ENV_MYSQL_PASSWORD -h$DB_PORT_3306_TCP_ADDR $DB_ENV_MYSQL_DATABASE'"
    usage: Pipe in a sql file.  `ahoy mysql-import < backups/live.sql`
  mysql-dump:
    cmd: "docker exec -it $(docker-compose ps -q cli) bash -c 'mysqldump -u$DB_ENV_MYSQL_USER -p$DB_ENV_MYSQL_PASSWORD -h$DB_PORT_3306_TCP_ADDR $DB_ENV_MYSQL_DATABASE'"
    usage: Dump data out into a file. `ahoy mysql-import > backups/local.sql`
  behat:
    cmd: "docker exec -it $(docker-compose ps -q cli) bash -c 'cd tests/behat && bin/behat -p docker {{args}}'"
    usage: Run the behat tests
  behat-init:
    cmd: "docker exec -it $(docker-compose ps -q cli) bash -c 'cd tests/behat && composer install'"
    usage: Run the behat tests
  reinstall:
    cmd: "ahoy drush -- si minimal -y && ahoy drush -- en custom_config -y && ahoy drush --  fra -y && ahoy drush cc all"
    usage: Reinstall a fresh version of the site.
  updb:
    cmd: "ahoy drush -- updb -y && ahoy drush cc all"
    usage: Install a backup, then run updb and cc all.
